services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawler
    env_file:
      - ./.dev.env
    depends_on:
      kafka-init:
        condition: service_completed_successfully
        restart: true
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    env_file:
      - ./.dev.env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_LOCALHOST}:9092,CONTROLLER://${KAFKA_LOCALHOST}:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA_HOST}:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - "9092:9092"

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    env_file:
      - ./.dev.env
    volumes:
      - ./kafka_init.sh:/kafka_init.sh
    command: ["sh", "kafka_init.sh"]
    depends_on:
      - kafka
    restart: on-failure

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
